baseURL = "https://ptcrash.dev"
title = "ptcrash"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "engimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Blog about mixed topics"
title404 = "Nothing's here!"

[params.assets]

favicon = "favicon.ico"
# customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]

[params.copyright]
prefix = "[Engimo theme by Acharcy](https://github.com/achary/engimo);"
holder = "John Martin;"
startYear = "2020"
suffix = "Text is available under [Creative Commons Attribution 4.0 International License ![CC BY 4.0](https://licensebuttons.net/l/by/4.0/80x15.png)](http://creativecommons.org/licenses/by/4.0/)"

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#da8388"
hideMainMenu = true
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
sidebar = ["about","sidebar_menu"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "ptcrash@pm.me"
linkedin = "passthecrash"
github = "ptcrash"
twitter = "ptcrash"

[params.comments]
enable = "utterances"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = true
issueTerm = "title" # pathname / url / title

[params.comments.utterances.github]
username = "ptcrash"
repository = "Website"
label = "comments"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.sidebar]]
name = "Home"
weight = -1
identifier = "Homepage"
url = "/"

[[menu.sidebar]]
name = "Blog"
weight = 50
identifier = "Blog"
url = "/posts"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1